# Generated by Django 6.0.3 on 2026-04-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_note_order_payment_received_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_received_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_carrier',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered_at',
        ),
    ]
