# Generated by Django 5.2.13 on 2026-06-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_address_alter_company_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('PKR', 'PKR (Rs.)'), ('SAR', 'SAR (SR)'), ('AED', 'AED (AED)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)')], default='USD', max_length=10),
        ),
    ]
