# Generated by Django 5.2.13 on 2026-05-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chathistory',
            new_name='ai_chat_his_user_id_e6e0d9_idx',
            old_name='ai_chat_his_user_id_2ad3f6_idx',
        ),
        migrations.RenameIndex(
            model_name='userproductinterest',
            new_name='user_produc_user_id_070288_idx',
            old_name='user_produc_user_id_80c0e6_idx',
        ),
        migrations.RenameIndex(
            model_name='userproductinterest',
            new_name='user_produc_product_eb33e1_idx',
            old_name='user_produc_product_8312de_idx',
        ),
    ]
